// SPDX-License-Identifier: MIT

export interface HighlightCase {
  name: string;
  grammar: string;
  source: string;
  expect: [string, string | null][];
}

export interface ScopeCase {
  name: string;
  grammar: string;
  source: string;
  scopes: (string | null)[];
}

const [E_ACUTE, GRINNING_FACE] = [0xe9, 0x1f600].map((codePoint) =>
  String.fromCodePoint(codePoint)
);

export const HIGHLIGHT_CASES: HighlightCase[] = [
  {
    name: 'x86 (GAS): code after multi-byte UTF-8 text is highlighted at the right place',
    grammar: 'asm_x86_gas',
    source: `// caf${E_ACUTE} ${GRINNING_FACE}\nnop # x\n`,
    expect: [
      [`// caf${E_ACUTE} ${GRINNING_FACE}`, 'comment'],
      ['nop', 'keyword'],
      ['# x', 'comment'],
    ],
  },
  {
    name: 'Assembly: local labels look the same where they are defined and where they are used',
    grammar: 'asm_auto',
    source: '.Lloop:\n    b .Lloop\n    .section .text\n',
    expect: [
      ['.Lloop', 'label'],
      ['b', 'keyword'],
      ['.Lloop', 'label'],
      ['.section', 'preproc'],
      ['.text', 'namespace'],
    ],
  },
  {
    name: 'Assembly: every current capture resolves the way Zed will paint it',
    grammar: 'asm_auto',
    source: [
      'main:',
      '.Lloop:',
      '    add x0, x1, x2, lsl #32 // c',
      '    movq $1, %rax',
      '    bl puts@PLT',
      '    .type main, %function',
      '    .type data, @object',
      '    .asciz "hi\\n"',
      "    mov x0, 'a",
      '    .size main, .-main',
      '#define N 4',
      '/* block */',
      '    mov x0, (1 + 2)',
      '',
    ].join('\n'),
    expect: [
      ['main', 'function.definition'],
      [':', 'punctuation.delimiter'],
      ['.Lloop', 'label'],
      ['add', 'keyword'],
      ['x0', 'variable.special'],
      [',', 'punctuation.delimiter'],
      ['lsl', 'keyword.operator'],
      ['#', 'punctuation.special'],
      ['32', 'number'],
      ['// c', 'comment'],
      ['movq', 'keyword'],
      ['$', 'punctuation.special'],
      ['1', 'number'],
      ['%rax', 'variable.special'],
      ['bl', 'keyword'],
      ['puts', 'constant'],
      ['@', 'punctuation.special'],
      ['PLT', 'attribute'],
      ['.type', 'preproc'],
      ['main', 'constant'],
      ['%function', 'type.builtin'],
      ['.type', 'preproc'],
      ['data', 'constant'],
      ['@', 'punctuation.special'],
      ['object', 'type.builtin'],
      ['.asciz', 'preproc'],
      ['"hi', 'string'],
      ['\\n', 'string.escape'],
      ['"', 'string'],
      ['mov', 'keyword'],
      ["'a", 'string'],
      ['.size', 'preproc'],
      ['main', 'constant'],
      ['.', 'constant.builtin'],
      ['-', 'operator'],
      ['#define', 'preproc'],
      ['/* block */', 'comment'],
      ['mov', 'keyword'],
      ['(', 'punctuation.bracket'],
      ['1', 'number'],
      ['+', 'operator'],
      ['2', 'number'],
      [')', 'punctuation.bracket'],
    ],
  },
  {
    name: 'ARM: shifts and immediates stay code, @ starts a comment',
    grammar: 'asm_arm',
    source: 'start:\n    ADD X0, X1, X2, LSL #32 @ trailing\n',
    expect: [
      ['start', 'function.definition'],
      ['ADD', 'keyword'],
      ['LSL', 'keyword.operator'],
      ['#', 'punctuation.special'],
      ['32', 'number'],
      ['@ trailing', 'comment'],
    ],
  },
  {
    name: 'ARM: registers, conditions, brackets, register lists and relocation specifiers',
    grammar: 'asm_arm',
    source: [
      '    ldr x0, [x1, #8]!',
      '    ld1 {v0.16b-v3.16b}, [x0], #64',
      '    csel x0, x1, x2, LT',
      '    add x0, x0, :lo12:sym',
      '    ldr r0, =value',
      '    ldm r0!, {r1, r2}^',
      '    ld1d {z0.d}, p0/z, [x0, #1, mul vl]',
      '    mov v1.s[2], w0',
      '    adrp x0, x1',
      '',
    ].join('\n'),
    expect: [
      ['ldr', 'keyword'],
      ['x0', 'variable.special'],
      [',', 'punctuation.delimiter'],
      ['[', 'punctuation.bracket'],
      ['x1', 'variable.special'],
      ['#', 'punctuation.special'],
      ['8', 'number'],
      [']', 'punctuation.bracket'],
      ['!', 'operator'],
      ['ld1', 'keyword'],
      ['{', 'punctuation.bracket'],
      ['v0.16b', 'variable.special'],
      ['-', 'operator'],
      ['v3.16b', 'variable.special'],
      ['}', 'punctuation.bracket'],
      ['csel', 'keyword'],
      ['x2', 'variable.special'],
      ['LT', 'keyword.operator'],
      ['add', 'keyword'],
      [':', 'punctuation.delimiter'],
      ['lo12', 'attribute'],
      [':', 'punctuation.delimiter'],
      ['sym', 'constant'],
      ['r0', 'variable.special'],
      ['=', 'punctuation.special'],
      ['value', 'constant'],
      ['ldm', 'keyword'],
      ['r0', 'variable.special'],
      ['!', 'operator'],
      ['^', 'operator'],
      ['z0.d', 'variable.special'],
      ['p0/z', 'variable.special'],
      ['mul', 'keyword.operator'],
      ['vl', 'constant'],
      ['v1.s', 'variable.special'],
      ['[', 'punctuation.bracket'],
      ['2', 'number'],
      [']', 'punctuation.bracket'],
      ['w0', 'variable.special'],
      ['adrp', 'keyword'],
      ['x0', 'variable.special'],
      ['x1', 'constant'],
    ],
  },
  {
    name: 'ARM: a register alias names a register, and its directive word is a directive',
    grammar: 'asm_arm',
    source: 'src .req x0\n    .cfi_offset x29, -16\n    .save {r4, lr}\n',
    expect: [
      ['src', 'variable.special'],
      ['.req', 'preproc'],
      ['x0', 'variable.special'],
      ['.cfi_offset', 'preproc'],
      ['x29', 'variable.special'],
      ['.save', 'preproc'],
      ['{', 'punctuation.bracket'],
      ['r4', 'variable.special'],
    ],
  },
  {
    name: 'ARM (Apple): L names are local in operands, LR stays a register and LT a condition',
    grammar: 'asm_arm_apple',
    source: [
      '    mov x0, LR',
      '    adrp x0, Ltmp0@PAGE',
      '    ldr x0, [x0, Ltmp0@PAGEOFF]',
      '    csel x0, x1, x2, LT',
      '    b LBB0_2',
      '',
    ].join('\n'),
    expect: [
      ['mov', 'keyword'],
      ['x0', 'variable.special'],
      ['LR', 'variable.special'],
      ['adrp', 'keyword'],
      ['Ltmp0', 'label'],
      ['@', 'punctuation.special'],
      ['PAGE', 'attribute'],
      ['[', 'punctuation.bracket'],
      ['Ltmp0', 'label'],
      ['PAGEOFF', 'attribute'],
      [']', 'punctuation.bracket'],
      ['LT', 'keyword.operator'],
      ['LBB0_2', 'label'],
    ],
  },
  {
    name: 'Assembly: ARM and x86 registers look the same, ARM brackets are brackets',
    grammar: 'asm_auto',
    source: '    movq %rax, %rbx\n    stp x29, x30, [sp, #-16]!\n    movw r0, #:lower16:sym\n',
    expect: [
      ['%rax', 'variable.special'],
      ['%rbx', 'variable.special'],
      ['x29', 'variable.special'],
      ['x30', 'variable.special'],
      ['[', 'punctuation.bracket'],
      ['sp', 'variable.special'],
      ['#', 'punctuation.special'],
      ['-', 'operator'],
      ['16', 'number'],
      [']', 'punctuation.bracket'],
      ['!', 'operator'],
      ['r0', 'variable.special'],
      ['#', 'punctuation.special'],
      ['lower16', 'attribute'],
      ['sym', 'constant'],
    ],
  },
  {
    name: 'ARM: suffix relocations, typed registers and NEON aliases',
    grammar: 'asm_arm',
    source: '    .word sym(GOT)\nsum .dn d4.f32\n    vadd d0.f32, d1.f32, d2.f32\n',
    expect: [
      ['.word', 'preproc'],
      ['sym', 'constant'],
      ['(', 'punctuation.bracket'],
      ['GOT', 'attribute'],
      [')', 'punctuation.bracket'],
      ['sum', 'variable.special'],
      ['.dn', 'preproc'],
      ['d4.f32', 'variable.special'],
      ['vadd', 'keyword'],
      ['d0.f32', 'variable.special'],
    ],
  },
  {
    name: 'ARM (Apple): literal pools, predicates, aliases and upper-case L mnemonics',
    grammar: 'asm_arm_apple',
    source: 'src .req x1\n    ldr x0, =_data\n    ld1d {z0.d}, p0/z, [x0]\n    LDP x0, x1, [sp]\n',
    expect: [
      ['src', 'variable.special'],
      ['.req', 'preproc'],
      ['x1', 'variable.special'],
      ['ldr', 'keyword'],
      ['=', 'punctuation.special'],
      ['_data', 'constant'],
      ['{', 'punctuation.bracket'],
      ['z0.d', 'variable.special'],
      ['p0/z', 'variable.special'],
      ['LDP', 'keyword'],
      ['sp', 'variable.special'],
    ],
  },
  {
    name: 'Assembly: conditions, literal pools, aliases and both relocation forms',
    grammar: 'asm_auto',
    source: [
      'src .req x1',
      '    csel x0, x1, x2, lt',
      '    ldr r0, =sym',
      '    .word sym(GOT)',
      '    add x0, x0, :lo12:sym',
      '',
    ].join('\n'),
    expect: [
      ['src', 'variable.special'],
      ['.req', 'preproc'],
      ['csel', 'keyword'],
      ['lt', 'keyword.operator'],
      ['=', 'punctuation.special'],
      ['sym', 'constant'],
      ['GOT', 'attribute'],
      ['lo12', 'attribute'],
    ],
  },
  {
    name: 'ARM (Apple): @PAGE is a relocation and ; starts a comment',
    grammar: 'asm_arm_apple',
    source: '_start:\n    adrp x0, _msg@PAGE\n    mov w0, #0 ; =0x0\n',
    expect: [
      ['_start', 'function.definition'],
      ['adrp', 'keyword'],
      ['_msg', 'constant'],
      ['@', 'punctuation.special'],
      ['PAGE', 'attribute'],
      ['#', 'punctuation.special'],
      ['0', 'number'],
      ['; =0x0', 'comment'],
    ],
  },
  {
    name: 'x86 (GAS): registers, # comments and ; separators',
    grammar: 'asm_x86_gas',
    source: 'start:\n    movq %rax, %rbx # save\n    nop; ret\n',
    expect: [
      ['movq', 'keyword'],
      ['%rax', 'variable.special'],
      ['%rbx', 'variable.special'],
      ['# save', 'comment'],
      ['nop', 'keyword'],
      [';', null],
      ['ret', 'keyword'],
    ],
  },
  {
    name:
      'ARM: numeric and dollar labels are labels, floats are numbers, assignments name constants',
    grammar: 'asm_arm',
    source: '1:\n    b 1b\n2$: b 2$\nSIZE = 16\n    .float 1.5, 0x1.8p0\n    .4byte 3\n',
    expect: [
      ['1', 'label'],
      ['b', 'keyword'],
      ['1b', 'label'],
      ['2$', 'label'],
      ['2$', 'label'],
      ['SIZE', 'constant'],
      ['=', null],
      ['16', 'number'],
      ['.float', 'preproc'],
      ['1.5', 'number'],
      ['0x1.8p0', 'number'],
      ['.4byte', 'preproc'],
      ['3', 'number'],
    ],
  },
  {
    name: 'x86 (GAS): macro names, parameters, arguments and glued names',
    grammar: 'asm_x86_gas',
    source: [
      '.macro gen name, op=nop, s:req',
      '\\name\\()_start:',
      '    no\\s',
      '    movq $\\@, %rax',
      '.endm',
      '    gen f, op=ret, s=p',
      '',
    ].join('\n'),
    expect: [
      ['.macro', 'preproc'],
      ['gen', 'function.special.definition'],
      ['name', 'variable.parameter'],
      ['op', 'variable.parameter'],
      ['nop', 'constant'],
      ['s', 'variable.parameter'],
      ['req', 'constant'],
      ['\\name', 'variable.parameter'],
      ['\\()', 'punctuation.special'],
      ['_start', 'label'],
      ['no', 'keyword'],
      ['\\s', 'variable.parameter'],
      ['movq', 'keyword'],
      ['\\@', 'variable.parameter'],
      ['%rax', 'variable.special'],
      ['.endm', 'preproc'],
      ['gen', 'keyword'],
      ['op', 'variable.parameter'],
      ['ret', 'constant'],
    ],
  },
  {
    name: 'ARM: conditional and repeat words are directives, the repeat parameter is a parameter',
    grammar: 'asm_arm',
    source: [
      '.ifdef DEBUG',
      '    nop',
      '.elseif SIZE',
      '.else',
      '.endif',
      '.irp r, x0, x1',
      '    mov \\r, #0',
      '.endr',
      '.rept 2',
      '.endr',
      '',
    ].join('\n'),
    expect: [
      ['.ifdef', 'preproc'],
      ['DEBUG', 'constant'],
      ['nop', 'keyword'],
      ['.elseif', 'preproc'],
      ['.else', 'preproc'],
      ['.endif', 'preproc'],
      ['.irp', 'preproc'],
      ['r', 'variable.parameter'],
      ['x0', 'constant'],
      ['\\r', 'variable.parameter'],
      ['.endr', 'preproc'],
      ['.rept', 'preproc'],
      ['2', 'number'],
      ['.endr', 'preproc'],
    ],
  },
  {
    name:
      'Assembly: a macro name is a constant, a function-like one a function, its parameters parameters',
    grammar: 'asm_auto',
    source: '#define N 4\n#define ADD(a, b) a + b\n#if N > 2\n#endif\n',
    expect: [
      ['#define', 'preproc'],
      ['N', 'constant'],
      ['4', null],
      ['#define', 'preproc'],
      ['ADD', 'function.special'],
      ['a', 'variable.parameter'],
      ['b', 'variable.parameter'],
      ['a + b', null],
      ['#if', 'preproc'],
      ['N > 2', null],
    ],
  },
  {
    name: 'x86 (GAS): the section a directive switches to is a namespace',
    grammar: 'asm_x86_gas',
    source:
      '    .section .rodata,"a",@progbits\n    .pushsection .data\n    .SECTION .bss\n    .text\n',
    expect: [
      ['.section', 'preproc'],
      ['.rodata', 'namespace'],
      ['"a"', 'string'],
      ['.pushsection', 'preproc'],
      ['.data', 'namespace'],
      ['.SECTION', 'preproc'],
      ['.bss', 'namespace'],
      ['.text', 'preproc'],
    ],
  },
  {
    name: 'ARM (Apple): segment and section are namespaces, L labels are local, .L labels are not',
    grammar: 'asm_arm_apple',
    source:
      '    .section __TEXT,__text,regular,pure_instructions\n_walk:\nLBB0_2:\n    b LBB0_2\n.Lx:\n    ret\n',
    expect: [
      ['.section', 'preproc'],
      ['__TEXT', 'namespace'],
      ['__text', 'namespace'],
      ['regular', 'constant'],
      ['_walk', 'function.definition'],
      ['LBB0_2', 'label'],
      ['.Lx', 'function.definition'],
    ],
  },
  {
    name: 'Assembly: comment characters inside strings stay string text',
    grammar: 'asm_auto',
    source: '.ascii " # x", "// y", "a\\n@b", "; z"\n',
    expect: [
      ['.ascii', 'preproc'],
      ['" # x"', 'string'],
      ['"// y"', 'string'],
      ['"a', 'string'],
      ['\\n', 'string.escape'],
      ['@b"', 'string'],
      ['"; z"', 'string'],
    ],
  },
  {
    name: 'Assembly: comments on preprocessor lines keep their comment color',
    grammar: 'asm_auto',
    source: '#endif /* X */\n#define X 1 // c\n#include "a//b.h"\n',
    expect: [
      ['#endif', 'preproc'],
      ['/* X */', 'comment'],
      ['#define', 'preproc'],
      ['X', 'constant'],
      ['1', null],
      ['// c', 'comment'],
      ['#include', 'preproc'],
      ['"a//b.h"', null],
    ],
  },
  {
    name: 'x86 (NASM): local labels, suffixed numbers, strings and ; comments',
    grammar: 'asm_x86_nasm',
    source: '.loop:\n    mov eax, 0FFh ; note\n    db \'x\', "y"\n',
    expect: [
      ['.loop', 'label'],
      ['mov', 'keyword'],
      ['0FFh', 'number'],
      ['; note', 'comment'],
      ['db', 'keyword'],
      ["'x'", 'string'],
      ['"y"', 'string'],
    ],
  },
];

export const SCOPE_CASES: ScopeCase[] = [
  {
    name:
      'Assembly: comments include both edges, strings exclude their quotes, preproc lines their end',
    grammar: 'asm_auto',
    source: [
      '<|>// c<|>',
      '/* b<|> */<|>',
      '.asciz <|>"<|>s<|>"<|>',
      '#define N 4<|>',
      'nop<|>',
      '',
    ].join('\n'),
    scopes: [
      'comment',
      'comment',
      'comment',
      'comment',
      null,
      'string',
      'string',
      null,
      'preproc',
      null,
    ],
  },
  {
    name:
      'Assembly: the end of a preprocessor line with a trailing comment is still the preproc scope',
    grammar: 'asm_auto',
    source: [
      '#endif /* X */<|>',
      '#else // !X<|>',
      '#define X 1 // c<|>',
      '#if A /* spans<|>',
      '   lines */<|>',
      'nop<|>',
      '',
    ].join('\n'),
    scopes: ['preproc', 'preproc', 'preproc', 'preproc', 'preproc', null],
  },
  {
    name: 'Assembly: trailing blanks on a preprocessor line stay in the preproc scope',
    grammar: 'asm_auto',
    source: '#define X 1   <|>\n#else <|>\n#endif /* X */  <|>\nnop  <|>\n',
    scopes: ['preproc', 'preproc', 'preproc', null],
  },
  {
    name:
      'x86 (GAS): the end of a preprocessor line with a trailing comment is still the preproc scope',
    grammar: 'asm_x86_gas',
    source: '#endif /* X */<|>\n#else // !X<|>\n',
    scopes: ['preproc', 'preproc'],
  },
  {
    name: 'x86 (GAS): a cursor after a comment character inside a string is in the string',
    grammar: 'asm_x86_gas',
    source: '.ascii " #<|> x"\n',
    scopes: ['string'],
  },
  {
    name: 'x86 (NASM): comment and string scopes',
    grammar: 'asm_x86_nasm',
    source: '; c<|>\ndb <|>"<|>s"\n',
    scopes: ['comment', null, 'string'],
  },
];
