name = "ARM Assembly (Apple)"
grammar = "asm_arm_apple"
modeline_aliases = ["arm64-apple", "apple-arm64", "darwin-arm64"]
line_comments = ["// ", "# ", "; "]
block_comment = { start = "/*", prefix = "", end = "*/", tab_size = 1 }
documentation_comment = { start = "/*", prefix = "* ", end = "*/", tab_size = 1 }
autoclose_before = ",;)]}"
brackets = [
  { start = "{", end = "}", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
  { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
  { start = "/*", end = " */", close = true, newline = false, not_in = ["string", "comment"] },
]
word_characters = [".", "$", "%"]
increase_indent_pattern = "^\\s*(?:[A-Za-z_.][A-Za-z0-9_.$]*|[0-9]+):|^[ \\t\\f\\v\\r]*(?:[A-Za-z0-9_.$\\\\]+[ \\t\\f\\v\\r]*:[ \\t\\f\\v\\r]*)*(?:(?:(?:[.][mM][aA][cC][rR][oO])(?:(?:\"(?:[^\"\\\\]|\\\\.)*(?:\"|\\\\?$)|'(?:\\\\.?|[^\\\\])?'?|/\\*(?:[^*]|\\*+[^*/])*\\*+/|[^A-Za-z0-9_.$\\\\\"';])(?:\"(?:[^\"\\\\]|\\\\.)*(?:\"|\\\\?$)|'(?:\\\\.?|[^\\\\])?'?|/\\*(?:[^*]|\\*+[^*/])*\\*+/|[^\"';])*)?|(?:[.][iI][fF]|[.][iI][fF][bB]|[.][iI][fF][cC]|[.][iI][fF][dD][eE][fF]|[.][iI][fF][eE][qQ]|[.][iI][fF][eE][qQ][sS]|[.][iI][fF][gG][eE]|[.][iI][fF][gG][tT]|[.][iI][fF][lL][eE]|[.][iI][fF][lL][tT]|[.][iI][fF][nN][bB]|[.][iI][fF][nN][cC]|[.][iI][fF][nN][dD][eE][fF]|[.][iI][fF][nN][eE]|[.][iI][fF][nN][eE][sS]|[.][iI][fF][nN][oO][tT][dD][eE][fF])(?:(?:\"(?:[^\"\\\\]|\\\\.)*(?:\"|\\\\?$)|'(?:\\\\.?|[^\\\\])?'?|/\\*(?:[^*]|\\*+[^*/])*\\*+/|[^A-Za-z0-9_.$\\\\\"';])(?:\"(?:[^\"\\\\]|\\\\.)*(?:\"|\\\\?$)|'(?:\\\\.?|[^\\\\])?'?|/\\*(?:[^*]|\\*+[^*/])*\\*+/|[^\"';])*)?|(?:[.][rR][eE][pP][tT]|[.][iI][rR][pP]|[.][iI][rR][pP][cC])(?:(?:\"(?:[^\"\\\\]|\\\\.)*(?:\"|\\\\?$)|'(?:\\\\.?|[^\\\\])?'?|/\\*(?:[^*]|\\*+[^*/])*\\*+/|[^A-Za-z0-9_.$\\\\\"';])(?:\"(?:[^\"\\\\]|\\\\.)*(?:\"|\\\\?$)|'(?:\\\\.?|[^\\\\])?'?|/\\*(?:[^*]|\\*+[^*/])*\\*+/|[^\"';])*)?)|(?:[.][eE][lL][sS][eE][iI][fF]|[.][eE][lL][sS][eE])(?:(?:\"(?:[^\"\\\\]|\\\\.)*(?:\"|\\\\?$)|'(?:\\\\.?|[^\\\\])?'?|/\\*(?:[^*]|\\*+[^*/])*\\*+/|[^A-Za-z0-9_.$\\\\\"';])(?:\"(?:[^\"\\\\]|\\\\.)*(?:\"|\\\\?$)|'(?:\\\\.?|[^\\\\])?'?|/\\*(?:[^*]|\\*+[^*/])*\\*+/|[^\"';])*)?)(?://.*|/\\*(?:[^*]|\\*+[^*/])*\\**$|;.*)?$"
decrease_indent_pattern = "^\\s*(?:[A-Za-z_.][A-Za-z0-9_.$]*|[0-9]+):"
debuggers = ["CodeLLDB", "GDB"]

[overrides.preproc]
line_comments = ["// "]
